apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-container
        image: satyazzz123/go-b:latest
        dependsOn:
        - name: mongo-deployment
          condition: Ready

---

apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 6000  # Port your API container listens on
      targetPort: 6000
  type: NodePort  # Expose the service on a NodePort
